export const CHAINS = {
  TESTNET: {
    AURA: "aura",
    AXELAR: "axelarnet",
    COMDEX: "comdex",
    EVMOS: "evmos",
    FETCH: "fetch",
    KUJIRA: "kujira",
    OSMOSIS: "osmosis-4",
    SEI: "sei",
    AURORA: "aurora",
    AVALANCHE: "avalanche",
    BINANCE: "binance",
    ETHEREUM: "ethereum-2",
    FANTOM: "fantom",
    MOONBEAM: "moonbeam",
    POLYGON: "polygon",
  },
  MAINNET: {
    ASSETMANTLE: "assetmantle",
    AVALANCHE: "avalanche",
    AXELAR: "axelarnet",
    BINANCE: "binance",
    COMDEX: "comdex",
    COSMOSHUB: "cosmoshub",
    CRESCENT: "crescent",
    ETHEREUM: "ethereum",
    EVMOS: "evmos",
    FANTOM: "fantom",
    FETCH: "fetch",
    INJECTIVE: "injective",
    JUNO: "juno",
    KI: "ki",
    KUJIRA: "kujira",
    MOONBEAM: "moonbeam",
    OSMOSIS: "osmosis",
    POLYGON: "polygon",
    REGEN: "regen",
    SECRET: "secret",
    STARGAZE: "stargaze",
    TERRA: "terra-2",
    EMONEY: "e-money",
  },
};
