export enum EvmChain {
  ETHEREUM = "ethereum",
  AVALANCHE = "avalanche",
  FANTOM = "fantom",
  POLYGON = "polygon",
  POLYGON_ZKEVM = "polygon-zkevm",
  MOONBEAM = "moonbeam",
  AURORA = "aurora",
  BINANCE = "binance",
  BNBCHAIN = "binance",
  ARBITRUM = "arbitrum",
  ARBITRUM_SEPOLIA = "arbitrum-sepolia",
  CELO = "celo",
  KAVA = "kava",
  BASE = "base",
  FILECOIN = "filecoin",
  OPTIMISM = "optimism",
  LINEA = "linea",
  MANTLE = "mantle",
  SCROLL = "scroll",
  SEPOLIA = "ethereum-sepolia",
  IMMUTABLE = "immutable",
  CENTRIFUGE_TESTNET = "centrifuge-2",
}
